### ISSUE TITLE
wrong expression

### ISSUE THREAD

**Issue by DenisSemakin** [stefanberger/linux-ima-namespaces#3]
Tiny and insignificant bug:
https://github.com/stefanberger/linux-ima-namespaces/blob/v5.18-rc3%2Bimans.v12.posted/STAGE3/0004-ima-Move-initialization-of-ima_tpm_chip-into-ima_ini.patch#L42

`-		if (ns->ima_tpm_chip)`
`+		if (!ns->ima_tpm_chip)`

**Comment by stefanberger** [comment]
Fixed. Thanks.

**Comment by DenisSemakin** [comment]
@stefanberger Please have a look at my email, I sent yesterday

**Comment by stefanberger** [comment]
I looked at it. The value of these patches is as good as their acceptance in the community. To increase their value we need more community acceptance and that's what would be need right now. That's all I can say at this point.

**Comment by DenisSemakin** [comment]
@stefanberger Ok, got your point, agree with that. Since my patches that are in progress and under development are based on yours (already mentioned patches) and these TPM patches are not accepted by community... could I ... for example push my patches to this repo (to another branch) and get your opinion for that?

**Comment by stefanberger** [comment]
I could have a look at your patches...

**Comment by stefanberger** [comment]
... but won't give a timeframe for when I will look at them .

**Comment by stefanberger** [comment]
You have seen the 80+ patches I have on top of the first 26? https://github.com/stefanberger/linux-ima-namespaces/tree/v5.18%2Bimans.v13.v5/STAGE3

**Comment by DenisSemakin** [comment]
@stefanberger Yes, of course I've seen them. Haven't analyzed them deeply yet but looks like these patches will cover all IMA namespaces stuff.
