### ISSUE TITLE
List of steps for IMA namespaces enablement

### ISSUE THREAD

**Issue by arijit8972** [stefanberger/linux-ima-namespaces#4]
Hi,

Would it be possible to provide or redirect me to a definite set of steps that would help me understand how I can enable IMA namespace for a particular container? I am failing to find a how-to-use kind of document that I can follow through.

**Comment by stefanberger** [comment]
IMA namespaces are not supported in the mainline kernel. I only have development branches in this tree here that provide support for IMA namespaces. Therefore, containers that you start with any runtime today won't support an IMA namespace.

**Comment by arijit8972** [comment]
Ok. Thank you for the clarification.
